// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TripsLog.Models;

#nullable disable

namespace TripsLog.Migrations
{
    [DbContext(typeof(TripContext))]
    [Migration("20251117002802_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TripsLog.Models.Accommodation", b =>
                {
                    b.Property<int>("AccommodationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccommodationId"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AccommodationId");

                    b.ToTable("Accommodations");

                    b.HasData(
                        new
                        {
                            AccommodationId = 1,
                            Email = "hotel@hotel.com",
                            Name = "Hotel",
                            Phone = "555-555-5555"
                        },
                        new
                        {
                            AccommodationId = 2,
                            Email = "staff@staybridge.com",
                            Name = "Staybridge Suites",
                            Phone = "212-555-1234"
                        },
                        new
                        {
                            AccommodationId = 3,
                            Name = "Camping"
                        });
                });

            modelBuilder.Entity("TripsLog.Models.Activity", b =>
                {
                    b.Property<int>("ActivityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ActivityId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ActivityId");

                    b.ToTable("Activities");

                    b.HasData(
                        new
                        {
                            ActivityId = 1,
                            Name = "Football Game"
                        },
                        new
                        {
                            ActivityId = 2,
                            Name = "Beach"
                        },
                        new
                        {
                            ActivityId = 3,
                            Name = "Hiking"
                        },
                        new
                        {
                            ActivityId = 4,
                            Name = "Museum"
                        },
                        new
                        {
                            ActivityId = 5,
                            Name = "Swimming"
                        },
                        new
                        {
                            ActivityId = 6,
                            Name = "Restaurant"
                        });
                });

            modelBuilder.Entity("TripsLog.Models.Destination", b =>
                {
                    b.Property<int>("DestinationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DestinationId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DestinationId");

                    b.ToTable("Destinations");

                    b.HasData(
                        new
                        {
                            DestinationId = 1,
                            Name = "Green Bay, Wisconsin"
                        },
                        new
                        {
                            DestinationId = 2,
                            Name = "New York, New York"
                        },
                        new
                        {
                            DestinationId = 3,
                            Name = "Tampa Bay, Florida"
                        });
                });

            modelBuilder.Entity("TripsLog.Models.Trip", b =>
                {
                    b.Property<int>("TripId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TripId"));

                    b.Property<int>("AccommodationId")
                        .HasColumnType("int");

                    b.Property<int>("DestinationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("TripId");

                    b.HasIndex("AccommodationId");

                    b.HasIndex("DestinationId");

                    b.ToTable("Trips");
                });

            modelBuilder.Entity("TripsLog.Models.TripActivity", b =>
                {
                    b.Property<int>("TripId")
                        .HasColumnType("int");

                    b.Property<int>("ActivityId")
                        .HasColumnType("int");

                    b.HasKey("TripId", "ActivityId");

                    b.HasIndex("ActivityId");

                    b.ToTable("TripActivities");
                });

            modelBuilder.Entity("TripsLog.Models.Trip", b =>
                {
                    b.HasOne("TripsLog.Models.Accommodation", "Accommodation")
                        .WithMany("Trips")
                        .HasForeignKey("AccommodationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TripsLog.Models.Destination", "Destination")
                        .WithMany("Trips")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Accommodation");

                    b.Navigation("Destination");
                });

            modelBuilder.Entity("TripsLog.Models.TripActivity", b =>
                {
                    b.HasOne("TripsLog.Models.Activity", "Activity")
                        .WithMany("TripActivities")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TripsLog.Models.Trip", "Trip")
                        .WithMany("TripActivities")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activity");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("TripsLog.Models.Accommodation", b =>
                {
                    b.Navigation("Trips");
                });

            modelBuilder.Entity("TripsLog.Models.Activity", b =>
                {
                    b.Navigation("TripActivities");
                });

            modelBuilder.Entity("TripsLog.Models.Destination", b =>
                {
                    b.Navigation("Trips");
                });

            modelBuilder.Entity("TripsLog.Models.Trip", b =>
                {
                    b.Navigation("TripActivities");
                });
#pragma warning restore 612, 618
        }
    }
}
