// <auto-generated />
using ManyToManyEF.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ManyToManyEF.Migrations
{
    [DbContext(typeof(RankenContext))]
    partial class RankenContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CourseStudent", b =>
                {
                    b.Property<int>("CoursesCourseId")
                        .HasColumnType("int");

                    b.Property<int>("StudentsStudentId")
                        .HasColumnType("int");

                    b.HasKey("CoursesCourseId", "StudentsStudentId");

                    b.HasIndex("StudentsStudentId");

                    b.ToTable("CourseStudent");

                    b.HasData(
                        new
                        {
                            CoursesCourseId = 1,
                            StudentsStudentId = 1
                        },
                        new
                        {
                            CoursesCourseId = 2,
                            StudentsStudentId = 1
                        },
                        new
                        {
                            CoursesCourseId = 3,
                            StudentsStudentId = 1
                        },
                        new
                        {
                            CoursesCourseId = 1,
                            StudentsStudentId = 2
                        },
                        new
                        {
                            CoursesCourseId = 2,
                            StudentsStudentId = 2
                        },
                        new
                        {
                            CoursesCourseId = 4,
                            StudentsStudentId = 2
                        },
                        new
                        {
                            CoursesCourseId = 1,
                            StudentsStudentId = 3
                        },
                        new
                        {
                            CoursesCourseId = 3,
                            StudentsStudentId = 3
                        },
                        new
                        {
                            CoursesCourseId = 4,
                            StudentsStudentId = 3
                        },
                        new
                        {
                            CoursesCourseId = 2,
                            StudentsStudentId = 4
                        });
                });

            modelBuilder.Entity("ManyToManyEF.Models.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseId"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CourseId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            CourseId = 1,
                            Title = "Web Development Fundamentals"
                        },
                        new
                        {
                            CourseId = 2,
                            Title = "Programming Fundamentals"
                        },
                        new
                        {
                            CourseId = 3,
                            Title = "Full Stack with JS"
                        },
                        new
                        {
                            CourseId = 4,
                            Title = "Full Stack with MS"
                        });
                });

            modelBuilder.Entity("ManyToManyEF.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<string>("FinancialAidStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            FinancialAidStatus = "Passed",
                            Name = "Alice Smith"
                        },
                        new
                        {
                            StudentId = 2,
                            FinancialAidStatus = "Passed",
                            Name = "Bob Jones"
                        },
                        new
                        {
                            StudentId = 3,
                            FinancialAidStatus = "Passed",
                            Name = "Charlie Johnson"
                        },
                        new
                        {
                            StudentId = 4,
                            FinancialAidStatus = "Passed",
                            Name = "Diana Prince"
                        });
                });

            modelBuilder.Entity("CourseStudent", b =>
                {
                    b.HasOne("ManyToManyEF.Models.Course", null)
                        .WithMany()
                        .HasForeignKey("CoursesCourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ManyToManyEF.Models.Student", null)
                        .WithMany()
                        .HasForeignKey("StudentsStudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
